# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Field Notes
tagline:          Where I show my work
url:              http://filbot.github.io
paginate:         1
baseurl:          /
author:
  name:           Filip Adamczyk
  url:            http://filbot.github.io
  email:          filip@filbot.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/filbot/filbot.github.io
